import React from 'react';
import { Route, Switch } from 'wouter';
import dashboard from './pages/dashboard/index';
import portfolio_properties from './pages/portfolio/properties';
import portfolio_units from './pages/portfolio/units';
import portfolio_leases from './pages/portfolio/leases';
import portfolio_tenants from './pages/portfolio/tenants';
import portfolio_owners from './pages/portfolio/owners';
import card_property_id from './pages/card/property/id';
import card_unit_id from './pages/card/unit/id';
import card_lease_id from './pages/card/lease/id';
import card_tenant_id from './pages/card/tenant/id';
import card_owner_id from './pages/card/owner/id';
import ops_accounting_overview from './pages/ops/accounting/overview';
import ops_accounting_rent_collection from './pages/ops/accounting/rent-collection';
import ops_accounting_expenses from './pages/ops/accounting/expenses';
import ops_accounting_financial_reports from './pages/ops/accounting/financial-reports';
import ops_accounting_tenant_ledgers from './pages/ops/accounting/tenant-ledgers';
import ops_accounting_collections_dashboard from './pages/ops/accounting/collections-dashboard';
import ops_accounting_collections_log from './pages/ops/accounting/collections-log';
import ops_accounting_payment_plans from './pages/ops/accounting/payment-plans';
import ops_accounting_deposits from './pages/ops/accounting/deposits';
import ops_accounting_transfers from './pages/ops/accounting/transfers';
import ops_accounting_subsidized_housing from './pages/ops/accounting/subsidized-housing';
import ops_accounting_assistance_programs from './pages/ops/accounting/assistance-programs';
import ops_ai_risk_summary from './pages/ops/ai/risk-summary';
import ops_ai_renewal_forecasting from './pages/ops/ai/renewal-forecasting';
import ops_ai_vacancy_analytics from './pages/ops/ai/vacancy-analytics';
import ops_ai_ml_leasing_logs from './pages/ops/ai/ml-leasing-logs';
import ops_legal_case_manager from './pages/ops/legal/case-manager';
import ops_legal_advanced from './pages/ops/legal/advanced';
import ops_legal_docs from './pages/ops/legal/docs';
import ops_legal_attorney_reports from './pages/ops/legal/attorney-reports';
import ops_comms_queue from './pages/ops/comms/queue';
import ops_comms_templates from './pages/ops/comms/templates';
import ops_comms_logs from './pages/ops/comms/logs';
import ops_work_work_orders from './pages/ops/work/work-orders';
import ops_work_vendors from './pages/ops/work/vendors';
import ops_work_materials_inventory from './pages/ops/work/materials-inventory';
import ops_work_smart_routing from './pages/ops/work/smart-routing';
import ops_work_ai_intelligence from './pages/ops/work/ai-intelligence';
import ops_work_build_repair_projects from './pages/ops/work/build-repair-projects';
import ops_work_capital_projects from './pages/ops/work/capital-projects';
import ops_reports from './pages/ops/reports';
import growth_inventory from './pages/growth/inventory';
import growth_marketing from './pages/growth/marketing';
import system_automation from './pages/system/automation';
import system_settings from './pages/system/settings';
import data_sync_audit from './pages/data/sync-audit';
import data_sync_management from './pages/data/sync-management';
import data_raw from './pages/data/raw';
import data_sync_logs from './pages/data/sync-logs';
import data_system_settings from './pages/data/system-settings';
import investor_dashboard from './pages/investor/dashboard';
import investor_portfolio_analytics from './pages/investor/portfolio-analytics';
import investor_financial_reports from './pages/investor/financial-reports';
import integrations_dropbox from './pages/integrations/dropbox';
import integrations_corelogic from './pages/integrations/corelogic';
import integrations_field_app from './pages/integrations/field-app';
import integrations_deal_room from './pages/integrations/deal-room';

export default function AppRoutes(){
  return (<Switch>
    <Route path="/dashboard" component={dashboard} />
    <Route path="/portfolio/properties" component={portfolio_properties} />
    <Route path="/portfolio/units" component={portfolio_units} />
    <Route path="/portfolio/leases" component={portfolio_leases} />
    <Route path="/portfolio/tenants" component={portfolio_tenants} />
    <Route path="/portfolio/owners" component={portfolio_owners} />
    <Route path="/card/property/:id" component={card_property_id} />
    <Route path="/card/unit/:id" component={card_unit_id} />
    <Route path="/card/lease/:id" component={card_lease_id} />
    <Route path="/card/tenant/:id" component={card_tenant_id} />
    <Route path="/card/owner/:id" component={card_owner_id} />
    <Route path="/ops/accounting/overview" component={ops_accounting_overview} />
    <Route path="/ops/accounting/rent-collection" component={ops_accounting_rent_collection} />
    <Route path="/ops/accounting/expenses" component={ops_accounting_expenses} />
    <Route path="/ops/accounting/financial-reports" component={ops_accounting_financial_reports} />
    <Route path="/ops/accounting/tenant-ledgers" component={ops_accounting_tenant_ledgers} />
    <Route path="/ops/accounting/collections-dashboard" component={ops_accounting_collections_dashboard} />
    <Route path="/ops/accounting/collections-log" component={ops_accounting_collections_log} />
    <Route path="/ops/accounting/payment-plans" component={ops_accounting_payment_plans} />
    <Route path="/ops/accounting/deposits" component={ops_accounting_deposits} />
    <Route path="/ops/accounting/transfers" component={ops_accounting_transfers} />
    <Route path="/ops/accounting/subsidized-housing" component={ops_accounting_subsidized_housing} />
    <Route path="/ops/accounting/assistance-programs" component={ops_accounting_assistance_programs} />
    <Route path="/ops/ai/risk-summary" component={ops_ai_risk_summary} />
    <Route path="/ops/ai/renewal-forecasting" component={ops_ai_renewal_forecasting} />
    <Route path="/ops/ai/vacancy-analytics" component={ops_ai_vacancy_analytics} />
    <Route path="/ops/ai/ml-leasing-logs" component={ops_ai_ml_leasing_logs} />
    <Route path="/ops/legal/case-manager" component={ops_legal_case_manager} />
    <Route path="/ops/legal/advanced" component={ops_legal_advanced} />
    <Route path="/ops/legal/docs" component={ops_legal_docs} />
    <Route path="/ops/legal/attorney-reports" component={ops_legal_attorney_reports} />
    <Route path="/ops/comms/queue" component={ops_comms_queue} />
    <Route path="/ops/comms/templates" component={ops_comms_templates} />
    <Route path="/ops/comms/logs" component={ops_comms_logs} />
    <Route path="/ops/work/work-orders" component={ops_work_work_orders} />
    <Route path="/ops/work/vendors" component={ops_work_vendors} />
    <Route path="/ops/work/materials-inventory" component={ops_work_materials_inventory} />
    <Route path="/ops/work/smart-routing" component={ops_work_smart_routing} />
    <Route path="/ops/work/ai-intelligence" component={ops_work_ai_intelligence} />
    <Route path="/ops/work/build-repair-projects" component={ops_work_build_repair_projects} />
    <Route path="/ops/work/capital-projects" component={ops_work_capital_projects} />
    <Route path="/ops/reports" component={ops_reports} />
    <Route path="/growth/inventory" component={growth_inventory} />
    <Route path="/growth/marketing" component={growth_marketing} />
    <Route path="/system/automation" component={system_automation} />
    <Route path="/system/settings" component={system_settings} />
    <Route path="/data/sync-audit" component={data_sync_audit} />
    <Route path="/data/sync-management" component={data_sync_management} />
    <Route path="/data/raw" component={data_raw} />
    <Route path="/data/sync-logs" component={data_sync_logs} />
    <Route path="/data/system-settings" component={data_system_settings} />
    <Route path="/investor/dashboard" component={investor_dashboard} />
    <Route path="/investor/portfolio-analytics" component={investor_portfolio_analytics} />
    <Route path="/investor/financial-reports" component={investor_financial_reports} />
    <Route path="/integrations/dropbox" component={integrations_dropbox} />
    <Route path="/integrations/corelogic" component={integrations_corelogic} />
    <Route path="/integrations/field-app" component={integrations_field_app} />
    <Route path="/integrations/deal-room" component={integrations_deal_room} />
    <Route>404 Not Found</Route>
  </Switch>);
}
