name: Verify
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript check
        run: npm run typecheck --if-present

      - name: Lint check
        run: npm run lint --if-present

      - name: Run unit tests
        run: npm test --if-present

      - name: Build app
        run: npm run build --if-present

      # ECC-specific audits
      - name: Run Replit Guard
        run: |
          if [ -f tools/replit_guard.sh ]; then
            bash tools/replit_guard.sh
          else
            echo "ℹ️ No guard script found, skipping"
          fi

      - name: Run Replit Audit
        run: |
          if [ -f tools/replit_audit.sh ]; then
            bash tools/replit_audit.sh
          else
            echo "ℹ️ No audit script found, skipping"
          fi

      - name: Run Playwright E2E tests
        run: |
          if [ -f playwright.config.ts ]; then
            npx playwright install --with-deps
            npx playwright test
          else
            echo "ℹ️ No Playwright config found, skipping"
          fi
