name: Verify

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Unit tests
        run: npm run test:unit --if-present
      - name: Build
        run: npm run build --if-present
      - name: Start dev server (background)
        run: |
          npm run dev &>/dev/null &
          echo "Waiting for dev server..."
          npx wait-on -t 60000 http://localhost:5173
      - name: E2E tests (Playwright)
        run: |
          npx playwright install --with-deps
          PLAYWRIGHT_BASE_URL=http://localhost:5173 npm run test:e2e
      - name: Upload Playwright artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-report
            test-results